### ISSUE TITLE
Why is there a genic annotation feature for promoters?

### ISSUE THREAD

**Issue by kdkorthauer** [mtello22/KorthauerLab#1]
https://github.com/mtello22/KorthauerLab/blob/3df8ec2c497323b50ef302e0ee84beee70f23dbf/VMRassociation/SupervisedLearning/Reports/CommitteeReport/CommitteeReport.Rmd#L227

Should they all have the same annotation (promoter)?

**Comment by mtello22** [comment]
You are totally right, I made a typo there. I checked again the numbers on the report and it seems to be in order.
